org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

minecraft_version=1.12.2

forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

mixin_gradle_version=0.7.+
mixin_version=0.8.5

shadow_gradle_version=8.1.1

mod_id=betterbiomeblend
mod_name=Betterer Biomer Blender
mod_group=fionathemortal.betterbiomeblend
mod_version=1.2.0
mod_author=["FionaTheMortal", "fonnymunkey"]
mod_description=Increases biome color blending radius and replaces the original blending algorithm with a more efficient one.

mixin_loader_class=fionathemortal.betterbiomeblend.BetterBiomeBlendPlugin